### ISSUE TITLE
missed id error

### ISSUE THREAD

**Issue by jariousroter** [elliotrodriguez/issue-tracker-improved#1]
**<label for="issueSeverityInput">Severity</label>
                <select class="form-control" id="issueSeverityInput">**
                <option value="Low">Low</option>
                <option value="Medium">Medium</option>
                <option value="High">High</option>

made this change, you had copied the div the three times but didn't change the id properly, please see code above.

**Comment by jariousroter** [comment]
`<label` for="issueSeverityInput">Severity</label>
                <select class="form-control" id="issueSeverityInput">
                <option value="Low">Low</option>
                <option value="Medium">Medium</option>
                <option value="High">High</option>

sorry, code didn't show

**Comment by elliotrodriguez** [comment]
@jariousroter can you please link a line? I copied the HTML content from the article also and it may very well require cleanup also. The SELECT dropdown does have an ID property. Can you clarify?

**Comment by jariousroter** [comment]
` <div class="form-group">
        <label for="issueDescInput">Severity</label>
        <select class="form-control" id="issueSeverityInput">
          <option value="Low">Low</option>
          <option value="Medium">Medium</option>
          <option value="High">High</option>
        </select>
      </div>
      <div class="form-group">
        <label for="issueDescInput">Assigned To</label>
        <input type="text" class="form-control" id="issueAssignedToInput" placeholder="Enter responsible ...">
      </div>`

both labels are assigned to 'issueDescInput', it's not a major issue i guess, how would you save these issues to a database?

**Comment by elliotrodriguez** [comment]
@jariousroter it's certainly possible to turn this into an express app with mongodb support. I'm working on a branch with mongo integration. Feel free to check it out.
